# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Draft', 1), ('Publish', 2)], default=1),
        ),
    ]
