# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180822_1650'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
