# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180822_2209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('post', 'email')]),
        ),
    ]
