# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180822_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(allow_unicode=True, default='', max_length=120),
        ),
    ]
