# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateField(null=True, verbose_name='publish date'),
        ),
    ]
